version: '3.8'
services:
  app:
    image: windbird:latest
    ports:
      - "8000:8000"
    volumes:
      - /windbird/data:/app/data
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    env_file: .env.prod
    volumes:
      - /windbird/mysql_data:/var/lib/mysql # 新增数据卷挂载
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
